name: chapter
description: dark novels model
version: 0.0.1
homepage: https://dark-novels.ru/
publish_to: none

environment:
  sdk: '>=2.13.0-0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.1.4
  equatable: ^2.0.3
  jiffy: ^5.0.0
  dark_novels_io:
    git:
      url: git@github.com:The28AWG/dark_novels_io.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

dependency_overrides:
  meta: ^1.7.0
  analyzer: ^3.2.0

flutter:
